/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:242860c9-9675-4867-8a66-0a34b3948079",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_A3GfztXeu",
    "aws_user_pools_web_client_id": "6msr21coug5o58iq1urs348od7",
    "oauth": {
        "domain": "cheapbook5df2abff-5df2abff-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.cheapbookdeals.com/",
        "redirectSignOut": "https://dev.cheapbookdeals.com/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://iyhacw6hyvhb7f2ysy4ostxzga.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-27b5rowfyjbnpav2uzs7aajwt4",
    "aws_cloud_logic_custom": [
        {
            "name": "emailnotificationapi",
            "endpoint": "https://k9lsxp7jke.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "cheapBookChatUsers-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "cheapBookChatRelation-dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "cheapbook8c72e6a76d77404fb1098092a1d46070173604-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
